// gets the server pkg
const express = require('express');
// allows the add routes
const router = express.Router();
// gets the db
const database = require('./database').data;

// given a name and password return matches
router.get('/api/:name/:password', function (request, response) {
    const username = request.params.name;
    const password = request.params.password;

    database.find({
        username: username,
        password: password
    }, function (
        error,
        docs
    ) {
        // checks for error
        if (!error) {
            response.send({
                status: 'success',
                users: docs,
            });
        } else {
            response.send({
                status: 'failed',
            });
        }
    });
});

// get by the user ID which is autogenerated by DB
router.get('api/:id', function (request, response) {
    const id = request.params.id;

    database.find({
        _id: id
    }, function (error, docs) {
        if (!error) {
            response.send({
                status: 'success',
                users: docs,
            });
        } else {
            response.send({
                status: 'failed',
            });
        }
    });
});

// register the user based no username and password
router.post('/api', function (request, response) {
    const username = request.body.username;
    const password = request.body.password;

    // template data entry without _id
    const newDoc = {
        username: username,
        password: password,
        x2times: [],
        x3times: [],
        x4times: [],
        x5times: [],
    };

    // adds the entry
    database.insert(newDoc, function (err, doc) {
        if (!err) {
            response.json({
                status: 'success',
                // returns the added document
                added: doc,
            });
        } else {
            response.json({
                status: 'failed',
            });
        }
    });

    // prevents default behavior of appending updates
    database.persistence.compactDatafile();
});

// updates the time given the order and the id of user
router.put('/api', function (request, response) {
    const time = request.body.time;
    const order = request.body.order;
    const id = request.body.id;

    // updating command
    database.update({
            _id: id
        }, {
            // pushs to the array given an object with field and value
            $push: getUpdaterObj(time, order)
        }, {
            // gives better response
            returnUpdatedDocs: true
        },
        function (err, numAffected, affectedDocs) {
            if (!err) {
                response.json({
                    // verbose response
                    status: 'success',
                    numAffected: numAffected,
                    affected: affectedDocs,
                });
            } else {
                response.json({
                    status: 'failed',
                });
            }
        }
    );

    // gives the object for $push to read
    function getUpdaterObj(result, order) {
        switch (order) {
            case 2:
                return {
                    x2times: result
                };
                break;
            case 3:
                return {
                    x3times: result
                };
                break;
            case 4:
                return {
                    x4times: result
                };
                break;
            case 5:
                return {
                    x5times: result
                };
                break;
        }
    }

    // prevent the default appending
    database.persistence.compactDatafile();
});

// delete the user with the given id
router.delete('/api', function (request, response) {
    const id = request.body.id;

    // first queries
    database.remove({
        _id: id
    }, {}, function (err, numRemoved) {
        if (!err) {
            response.json({
                status: 'success',
                numRemoved: numRemoved,
            });
        } else {
            response.json({
                status: 'failed',
            });
        }
    });

    // prevents default
    database.persistence.compactDatafile();
});

module.exports = router;